 <channel id="temperature" typeId="temperature" />
     <channel id="fanSpeed"                          typeId=""              />
     <channel id="tempInside"                        typeId=""              />
     <channel id="tempOutside"                       typeId=""              />
     <channel id="tempExhaust"                       typeId=""              />
     <channel id="tempIncomming"                     typeId=""              />
     <channel id="powerState"                        typeId=""              />
     <channel id="cO2AdjustState"                    typeId=""              />
     <channel id="humidityAdjustState"               typeId=""              />
     <channel id="heatingState"                      typeId=""              />
     <channel id="filterGuardIndicator"              typeId=""              />
     <channel id="heatingIndicator"                  typeId=""              />
     <channel id="faultIndicator"                    typeId=""              />
     <channel id="serviceReminderIndicator"          typeId=""              />
     <channel id="humidity"                          typeId=""              />
     <channel id="basicHumidityLevel"                typeId=""              />
     <channel id="humiditySensor1"                   typeId=""              />
     <channel id="humiditySensor2"                   typeId=""              />
     <channel id="cO2High"                           typeId=""              />
     <channel id="cO2Low"                            typeId=""              />
     <channel id="cO2SetPointHigh"                   typeId=""              />
     <channel id="cO2SetPointLow"                    typeId=""              />
     <channel id="fanSpeedMax"                       typeId=""              />
     <channel id="fanSpeedMin"                       typeId=""              />
     <channel id="dCFanInputAdjustment"              typeId=""              />
     <channel id="dCFanOutputAdjustment"             typeId=""              />
     <channel id="inputFanStopThreshold"             typeId=""              />
     <channel id="heatingSetPoint"                   typeId=""              />
     <channel id="preHeatingSetPoint"                typeId=""              />
     <channel id="hrcBypassThreshold"                typeId=""              />
     <channel id="cellDefrostingThreshold"           typeId=""              />
     <channel id="adjustmentIntervalMinutes"         typeId=""              />
     <channel id="automaticHumidityLevelSeekerState" typeId=""              /> 
     <channel id="boostSwitchMode"                   typeId=""              /> 
     <channel id="radiatorType"                      typeId=""              /> 
     <channel id="cascadeAdjust"                     typeId=""              /> 
     <channel id="maxSpeedLimitMode"                 typeId=""              /> 
     <channel id="serviceReminder"                   typeId=""              />
     <channel id="postHeatingOn"                     typeId=""              />
     <channel id="damperMotorPosition"               typeId=""              />
     <channel id="faultSignalRelayClosed"            typeId=""              />
     <channel id="supplyFanOff"                      typeId=""              />
     <channel id="preHeatingOn"                      typeId=""              />
     <channel id="exhaustFanOff"                     typeId=""              />
     <channel id="firePlaceBoosterClosed"            typeId=""              />
     <channel id="incommingCurrent"                  typeId=""              />
     <channel id="lastErrorNumber"                   typeId=""              />
     <channel id="inEfficiency"                      typeId=""              />
     <channel id="outEfficiency"                     typeId=""              />
     <channel id="averageEfficiency"                 typeId=""              />